name: Merge PR into master

on:
  push:
    branches:
      - master

jobs:
  run-on-pr-merge:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions'

    env:
      SOURCE: ${{ github.workspace }}/source/pymunge

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Increase minor version
        run: |
          python ${{ env.SOURCE }}/make.py version --increment minor

      - name: Commit changes
        run: |
          git add ${{ env.SOURCE }}/version.py
          git commit -m "Increase minor version" || echo "No changes"

      - name: Push tag
        run: |
          python ${{ env.SOURCE }}/make.py git --tag
          git push
