name: Merge PR into master

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  run-on-pr-merge:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions'

    env:
      DIR_DOCS: ${{ github.workspace }}/docs
      DIR_SOURCE: ${{ github.workspace }}/source

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         fetch-depth: 500
         token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Increase minor version
        run: |
          python ${{ env.DIR_SOURCE }}/pymunge/make.py version --increment minor

      - name: Commit changes
        run: |
          git add ${{ env.DIR_SOURCE }}/pymunge/version.py
          git commit -m "Increase minor version" || echo "No changes"

      - name: Push tag
        continue-on-error: true
        run: |
          python ${{ env.DIR_SOURCE }}/pymunge/make.py git --tag

      - name: Autogen docs
        run: |
          sphinx-apidoc -o ${{ env.DIR_DOCS }}/source ${{ env.DIR_SOURCE }}/pymunge

      - name: Build docs
        run: |
          sphinx-build -b html -E ${{ env.DIR_DOCS }}/source ${{ env.DIR_DOCS }}/build

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ env.DIR_DOCS }}/build
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
